<a href="https://colab.research.google.com/github/menasiraziz/Convnet/blob/master/convnet2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

In [0]:
from numpy.lib.stride_tricks import as_strided


def strided_convolution3D(image, weight, stride):
    m,ch,im_h, im_w = image.shape
    f,t,f_h, f_w = weight.shape
    out_shape = (m,ch,1 + (im_h - f_h) // stride, 1 + (im_w - f_w) // stride, f_h, f_w)
    out_strides = (image.strides[0],image.strides[1],image.strides[2] * stride, image.strides[3] * stride, image.strides[2], image.strides[3])
    windows = as_strided(image, shape=out_shape, strides=out_strides)
    return np.einsum('mcopjk,ecjk->meop',windows,weight)

def mx_pool(img,s): # function takes advatange of row order of numpy array
  m,ch,n,n=img.shape # flatten all images into stride 
  c=img.reshape(-1,s) #change s to change horizontal stride
  ind=np.argmax(c,axis=1)
  ind1=np.ravel_multi_index([np.arange(ind.shape[0]),ind], (ind.shape[0],s))
  d=img.flatten()[ind1]
  g=d.reshape(-1,s,int(n/s)) #probably i need to change s in the middle to change vertical stride

  h=g.argmax(axis=1)
  i1=np.arange(g.shape[0]) # varies along images in data 
  i2=np.arange(g.shape[2]) # varies along col axis in indices
  ss=i1[:,np.newaxis]*n+g.shape[2]*h+i2 # i2 is varying along col and i1 is varying along batch and row dim
  return ind1[ss.flatten()]


import numpy as np
from numpy.lib.stride_tricks import as_strided


def strided_convolution3D1_g(image, weight, stride):
    m,ch,im_h, im_w = image.shape
    f,t,f_h, f_w = weight.shape
    #print(m)
    out_shape = (m,ch,1 + (im_h - f_h) // stride, 1 + (im_w - f_w) // stride, f_h, f_w)
    out_strides = (image.strides[0],image.strides[1],image.strides[2] * stride, image.strides[3] * stride, image.strides[2], image.strides[3])
    windows = as_strided(image, shape=out_shape, strides=out_strides)
    #print(windows.shape)
    #print(windows)
    return np.einsum('meopjk,ecjk->mecop',windows,weight)
    #return np.einsum('meopjk,ecjk->meop',windows,weight)
    #return np.einsum('meopjk,ecjk->mecop',windows,weight)

def strided_convolution3D_grad1(image, weight, stride):
    m,ch,im_h, im_w = image.shape
    m1,m2,f_h, f_w = weight.shape
    
    #print(m)
    out_shape = (m,ch,1 + (im_h - f_h) // stride, 1 + (im_w - f_w) // stride, f_h, f_w)
    out_strides = (image.strides[0],image.strides[1],image.strides[2] * stride, image.strides[3] * stride, image.strides[2], image.strides[3])
    windows = as_strided(image, shape=out_shape, strides=out_strides)
    #print(windows.shape)
    #print(windows[0])
    #print(windows*gg1)
    return np.einsum('mcopjk,mejk->mecop',windows,weight)


In [0]:
class ConvLayer:
  def __init__(self,in_ch=1,out_ch=1,kernel=(2,2),stride=1):
    self.filters=np.random.randn(out_ch,in_ch,kernel[0],kernel[1])
    self.stride=stride

  def feedforward(self,x):
    self.out=strided_convolution3D(x,self.filters,self.stride)
    return self.out
  def grad(self,x,loss_grad):
    self.df=strided_convolution3D_grad1(x,loss_grad,1).sum(axis=0)
    gg=np.rot90(loss_grad,2,axes=(2,3))
    gg1=np.pad(gg, ((0, 0),(0, 0),(1, 1),(1,1)), 'constant', constant_values=(0))
    ooo=strided_convolution3D1_g(gg1,self.filters,1)
    return np.rot90(ooo,2,axes=(3,4)).sum(axis=1)

class FC_Layer:
  def __init__(self,i_dim,out_dim):
    self.W=np.random.randn(i_dim,out_dim)
    self.dw=np.zeros(self.W.shape)
  def feedforward(self,x):
    self.out=np.dot(x,self.W)
    return self.out
  def grad(self,x,loss_grad):
    return self.W*loss_grad[:,np.newaxis]

class Network:
  def __init__(self):
    self.n=3
    self.in_ch=2
    self.m=2
    self.f=2
    self.cs=1
    self.o_ch=2

    self.conv1=ConvLayer(in_ch=self.in_ch,out_ch=self.o_ch,kernel=(self.f,self.f),stride=self.cs)
    cos=self.n-self.f+1
    self.FC1=FC_Layer(self.o_ch*cos*cos,1)

  def gen_images(self):
    return np.random.randn(self.m,self.in_ch,self.n,self.n)

  def feedforward(self,x):
    c1=self.conv1.feedforward(x)
    f1=self.FC1.feedforward(c1.reshape(c1.shape[0],-1))
    return f1
  def backpropagate(self,x,y,yhat):
    loss_grad=2*(yhat-y)
    gradF1=self.FC1.grad(self.conv1.out.reshape(loss_grad.shape[0],-1),loss_grad).reshape(self.conv1.out.shape)
    print(gradF1.shape)
    gradC1=self.conv1.grad(x,gradF1)
    print(gradC1.shape)
    print(gradC1)

  def loss(self,y,yhat):
    return np.sum(np.square(y-yhat))

  def num_grad(self,x,y):
    ep=np.zeros(x.shape)
    dw=np.zeros(x.shape)
    for dd in range(x.shape[0]):
      for k in range(x.shape[1]):
       for i in range(x.shape[2]):
         for j in range(x.shape[3]):

           ep[dd,k,i,j]=1e-4
           yhat1=self.feedforward(x+ep)
           yhat2=self.feedforward(x-ep)
           #print(yhat1.shape)
           dw[dd,k,i,j]=(self.loss(y,yhat1)-self.loss(y,yhat2))/2e-4
           ep[dd,k,i,j]=0

    return dw

In [112]:
np.random.seed(100)
nn=Network()
img=nn.gen_images()*10
y=np.random.randn(img.shape[0],1)
yhat=nn.feedforward(img)
nn.backpropagate(img,y,yhat)
nn.num_grad(img,y)

(2, 2, 2, 2)
(2, 2, 3, 3)
[[[[  2.14308401  -6.41087007   2.56684851]
   [ -1.85725554  11.08632085  -0.6439289 ]
   [ -1.34132861  -3.10579497  -0.2900457 ]]

  [[ -5.04500648   3.99176224   6.15496469]
   [  2.36960656   2.15898573  -8.6917963 ]
   [ -0.91648844  -1.09747722   4.42021565]]]


 [[[-17.78687048  53.20804735 -21.30397206]
   [ 15.41459111 -92.01270314   5.34439146]
   [ 11.13257256  25.7770449    2.40728096]]

  [[ 41.87184278 -33.13027279 -51.08411952]
   [-19.6669308  -17.91884938  72.13896151]
   [  7.60654324   9.10868876 -36.68629077]]]]


array([[[[  2.14308401,  -6.41087007,   2.56684851],
         [ -1.85725554,  11.08632085,  -0.6439289 ],
         [ -1.34132861,  -3.10579497,  -0.2900457 ]],

        [[ -5.04500648,   3.99176224,   6.15496469],
         [  2.36960656,   2.15898573,  -8.6917963 ],
         [ -0.91648844,  -1.09747722,   4.42021565]]],


       [[[-17.78687048,  53.20804735, -21.30397206],
         [ 15.41459111, -92.01270314,   5.34439146],
         [ 11.13257256,  25.7770449 ,   2.40728096]],

        [[ 41.87184278, -33.13027279, -51.08411952],
         [-19.6669308 , -17.91884937,  72.13896151],
         [  7.60654324,   9.10868876, -36.68629077]]]])

In [68]:
np.random.seed(0)
n=5
lay=FC_Layer(n,1)
m=3
x=np.random.randn(m,n)
y=np.random.randn(m,1)
yhat=lay.feedforward(x)
loss_grad=2*(yhat-y)
lay.grad(x,loss_grad).reshape(-1,n)

array([[ 5.63290227,  1.27776619,  3.12526747,  7.15553164,  5.9634124 ],
       [ 7.15809189,  1.62373984,  3.97147876,  9.09299515,  7.57809241],
       [-2.72464564, -0.61805796, -1.51169788, -3.4611444 , -2.88451403]])

In [43]:
loss_grad

array([[5.45294691],
       [4.98561353],
       [2.94279091]])

In [55]:
ll=lay.W*loss_grad[:,np.newaxis]
ll.flatten()

array([9.61928379, 2.18203601, 8.79488324, 1.99502919, 5.1912372 ,
       1.17757899])

In [47]:
lay.W*loss_grad[0]

array([[9.61928379],
       [2.18203601]])